---
title: "Using `httr`"
output: html_document
---

Taking a step in a new direction using the `httr` package. Just came out. Appears to have higher versatility with web extraction. First, see the instructions for the function, which can be found [here]("http://cran.r-project.org/web/packages/httr/httr.pdf") and [here]("http://cran.r-project.org/web/packages/httr/vignettes/quickstart.html")

```{r}
install.packages("httr")
install.packages("stringi")
require(httr)
require(stringi)
```


```{r}
#GET() gets urls
r <- GET("http://httpbin.org/get")
content(r, "text") # Content accesses the content of the message. 
content(r, "text", encoding = "ISO-8859-1") #When you can't trust the encoding.
content(r,"raw") #The raw sequence vector that the request sent back
str(content(r,"parsed")) #httr has a number a ways to get at the info
headers(r)

#cookies
r <- GET("http://httpbin.org/cookies", set_cookies("MeWant" = "cookies"))
content(r)$cookies

news <- GET("http://www.bbc.com/news/")
content(news,"parsed")
headers(news)
html(news) %>% html_nodes(.,"a")

#the function can get a whole range of things
httr.cran <- content(GET("http://cran.r-project.org/web/packages/httr/httr.pdf")) #Extracted a PDF into a raw data format

#handle()  preserves settings and cookies across multiple requests. 
google <- handle("http://google.com")

#HEAD() gets url headers
HEAD("http://google.com")$header
HEAD("http://bbc.com")$header


r <- VERB("PROPFIND", "http://svn.r-project.org/R/tags/",add_headers(depth = 1), verbose())
stop_for_status(r)
content(r)

bbc <- GET("http://www.bbc.com/news/world-latin-america-31033096")
status_code(bbc)
str(content(bbc))
content(bbc,"text")
#to figure out encoding
stringi::stri_enc_detect(content(bbc, "raw"))
content(bbc,"text",encoding="UTF-8")

str(content(bbc,"parsed"))

bbc <- GET("http://www.bbc.com/news/world-latin-america-31033096", add_headers(Name = "Hadley"))
str(content(bbc)$headers)
status_code(bbc)
```


#### TM package
```{r}
require(tm)
tt <- readPDF(PdftotextOptions = "-layout")
rr <- tt(elem=list(uri="/Users/Ericdunford/Desktop/test.pdf"),language="en",id="id1")
rr[1:15]
readPDF("/Users/Ericdunford/Desktop/test.pdf",engine="xpdf",control="info")
```

