---
title: "Web_Scrapping Practice"
output: html_document
---

Will attempt to scrape the following url. http://www.bbc.com/news/world-europe-30878406

The goal is to build a data frame of all the top stories of the day. 
```{r}
require(rjson)
require(RCurl)
require(XML)
url <- "http://www.bbc.com/news/world-europe-30878406"
raw.data <- getURL(url,encoding="UTF-8")
parsed.data <- htmlParse(raw.data)

xpathSApply(parsed.data,"//h1",xmlValue) #title
xpathSApply(parsed.data,
            "//*[@id='main-content']/div[2]/div[1]/span[1]/span[1]",
            xmlValue) #publishing date
xpathSApply(parsed.data,"//*[@id='main-content']/div[2]/div[1]/p",xmlValue) #story
```

Let's see if this pattern holds across other bbc stories.
```{r}
url <- "http://www.bbc.com/news/world-asia-30902237"
raw.data <- getURL(url,encoding="UTF-8")
parsed.data <- htmlParse(raw.data)

xpathSApply(parsed.data,"//h1",xmlValue) #title
xpathSApply(parsed.data,
            "//*[@id='main-content']/div[2]/div[1]/span[1]/span[1]",
            xmlValue) #publishing date
xpathSApply(parsed.data,"//*[@id='main-content']/div[2]/div[1]/p",xmlValue) #story
```

It worked! So now we need a loop to find all the stories for a particular subject.

```{r}
url <- "http://www.bbc.com/news/world-asia-30902237"

#Webscrapper just for title and date of story
bbcScrapper <- function(url){
  require(RCurl)
  require(XML)
  raw.data <- getURL(url,encoding="UTF-8")
  parsed.data <- htmlParse(raw.data)
  story.title <- xpathSApply(parsed.data,"//h1",xmlValue) 
  story.date <- xpathSApply(parsed.data,
                            "//*[@id='main-content']/div[2]/div[1]/span[1]/span[1]",
                            xmlValue) 
  c(story.title,story.date)
  }
bbcScrapper("http://www.bbc.com/news/science-environment-30888767")
```

Let's step this up. Here I will scan three BBC articles and pur them into a dataframe. 

```{r}
urls <- c("http://www.bbc.com/news/world-us-canada-30908095","http://www.bbc.com/news/world-europe-30907443","http://www.bbc.com/news/science-environment-30888767")

#Expanding the function to deal for when date is NULL
bbcScrapper <- function(url){
  require(RCurl)
  require(XML)
  raw.data <- getURL(url,encoding="UTF-8")
  parsed.data <- htmlParse(raw.data)
  story.title <- xpathSApply(parsed.data,"//h1",xmlValue) 
  story.date <- xpathSApply(parsed.data,
                            "//*[@id='main-content']/div[2]/div[1]/span[1]/span[1]",
                            xmlValue) 
  if (is.null(story.date)){
    story.date <- xpathSApply(parsed.data, "//span[@class='date']",xmlValue)
  }
  return(c(story.title,as.character(story.date)))
  }
bbc <- sapply(urls,bbcScrapper) %>% data.frame
head(bbc)

#Another more efficient approach...if not a little archaic.
require(plyr)
bbc <- ldply(urls,bbcScrapper)
bbc
```


